[deps]
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"

[compat]
Chairmarks = "1"
CUDA = "5"
OhMyThreads = "0.7"
OrdinaryDiffEq = "6"
SciMLBase = "2"
CommonSolve = "0.2"
