name = "LockstepODE"
uuid = "6148aecd-d198-440c-a04f-51208fe3c037"
authors = ["Kyle Beggs <beggskw@gmail.com> and contributors"]
version = "2.0.0"

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[weakdeps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[extensions]
LockstepODEMTKExt = "ModelingToolkit"

[compat]
ModelingToolkit = "9, 10"
OrdinaryDiffEq = "6"
SciMLBase = "2"
julia = "1.10"
