name = "LockstepODE"
uuid = "6148aecd-d198-440c-a04f-51208fe3c037"
authors = ["Kyle Beggs <beggskw@gmail.com> and contributors"]
version = "2.0.0"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[extensions]
LockstepODEAMDGPUExt = ["AMDGPU", "KernelAbstractions"]
LockstepODECUDAExt = ["CUDA", "KernelAbstractions"]
LockstepODEMTKExt = "ModelingToolkit"
LockstepODEMetalExt = ["Metal", "KernelAbstractions"]
LockstepODEoneAPIExt = ["oneAPI", "KernelAbstractions"]

[extras]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["CommonSolve", "ModelingToolkit", "OrdinaryDiffEq", "SciMLBase", "Statistics", "Test", "TestItemRunner", "TestItems"]

[compat]
AMDGPU = "1"
CUDA = "5"
CommonSolve = "0.2"
KernelAbstractions = "0.9"
Metal = "1"
ModelingToolkit = "9, 10"
OhMyThreads = "0.7, 0.8"
OrdinaryDiffEq = "6"
SciMLBase = "2"
julia = "1.10"
oneAPI = "1"
