name = "LockstepODE"
uuid = "6148aecd-d198-440c-a04f-51208fe3c037"
version = "0.0.1"
authors = ["Kyle Beggs <beggskw@gmail.com> and contributors"]

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[extensions]
LockstepODEAMDGPUExt = "AMDGPU"
LockstepODECUDAExt = "CUDA"
LockstepODEMetalExt = "Metal"
LockstepODEoneAPIExt = "oneAPI"

[compat]
AMDGPU = "0.8, 0.9, 1"
CUDA = "4, 5"
KernelAbstractions = "0.9"
Metal = "0.5, 1"
OhMyThreads = "0.8.3"
OrdinaryDiffEq = "6"
julia = "1.10"
oneAPI = "1, 2"
